version: '3.9'
services:
  web:
    build: .
    volumes:
      - ./src/:/var/www/html/
    ports:
      - '8083:80'
    depends_on:
      - db

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

  adminer:
    image: adminer
    depends_on:
      - db
    restart: always
    ports:
      - 8080:8080
