version: '3.3'
services:
  web:
    build: .
    volumes:
      - ./src/:/var/www/html/
    ports:
      - '80:80'
    depends_on:
      - db

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.8.1
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '8081:80'
    depends_on:
      - db

  adminer:
    image: adminer
    depends_on:
      - db
    restart: always
    ports:
      - 8080:8080
